<a href="https://colab.research.google.com/github/NierodkaGrow/Python_new/blob/main/04_machine_learning/Sklearn_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Scikit-learn
>Strona biblioteki: [https://scikit-learn.org](https://scikit-learn.org)  
>
>Dokumentacja/User Guide: [https://scikit-learn.org/stable/user_guide.html](https://scikit-learn.org/stable/user_guide.html)

>
>Aby zainstalować bibliotekę scikit-learn, użyj polecenia poniżej:
```
pip install scikit-learn
```
>Aby zaktualizować bibliotekę scikit-learn, użyj polecenia poniżej:
```
pip install -q --upgrade scikit-learn
```

Główne kategorie uczenia maszynowego:
* Uczenie Nadzorowane:
    - klasyfikacja (modele klasyfikacji) - podajemy wektor danych, który ma przypisaną etykietę, klasę, label
    - regresja (modele regresyjne) - przypisana jest tu pewna wartość do modelu danych
* Uczenie Nienadzorowane:
    - klasteryzacja - label, etykiety nie mamy, musimy znależć na podstawie naszych danych zależności, klastry
    - redukcja wymiarowości - nie mamy danych oznaczonych, musimy te dane pogrupować, wydobyć z nich wzorce

Importowanie biblioteki

In [ ]:
import sklearn
sklearn.__version__ 

'0.22.2.post1'

### 1. KLASYFIKACJA

Import standardowych danych z biblioteki sklearn; ustawienie ziarna losowego; przypisanie danych do zmiennej; załadowanie danych funkcją load_iris(); wynikiem surowe dane

In [ ]:
import numpy as np
from sklearn import datasets

np.random.seed(10)
raw_data = datasets.load_iris()
raw_data

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

Sprawdzenie jakie są klucze w słowniku naszych surowych danych

In [ ]:
raw_data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

Wyświetlenie opisu danych

In [ ]:
print(raw_data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

### Przygotowanie danych do modelu 

nasze dane są pod kluczem data zobacz wyżej na ten klucz. Wycięcie row_data (to tablica numpy array)

In [ ]:
raw_data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Przypisanie danych do zmiennej data. Wyświetlenie zmiennej docelowej - target (pod tą zmienną są odpowiednio przypisane numery klas 0,1,2; Jest 50 próbek dla każdej klasy)

In [ ]:
data = raw_data.data
raw_data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Ułożenie danych pod zmienną data. Pod zmienną target - dane, które będziesz się starał przewidzieć

In [ ]:
data = raw_data.data
target = raw_data.target

Sprawdzenei kształtu danych

In [ ]:
print(data.shape) 
print(target.shape)

(150, 4)
(150,)


### Dziele danych na dane testowe i dane treningowe

Standardowo dzieli się dane na: zbiór TRENINGOWY (na nim trenujesz model), zbiór TESTOWY (na nim oceniasz jak model dziła). Trenujemy model na danych treningowych a oceniamy na danych testowych. Ważne aby model nie widział wcześniej danych testowych - ponieważ nadmiernie dopasuje sie do danych, a to nie ma sensu.

Importowanie funkcji train_test_split() do podziału danych. Funkcja zwraca 4 obiekty np.: data_train (zbiór danych treningowych), data_test (zbiór danych testowych). Przekazanie do funkcji danych. Wyznaczenie miejsca 30% na dane testowe, a 70% na dane treningowe.

In [ ]:
from sklearn.model_selection import  train_test_split
data_train, data_test, target_train, target_test = train_test_split(data, target, test_size=0.3)

Sprawdzam dane w zbiorze treningowym i testowym

Jest 105 przypadków w zbiorze treningowym

In [ ]:
print(data_train.shape)
print(target_train.shape)

(105, 4)
(105,)


W zbiorze testowym jest 45 przypadków

In [ ]:
print(data_test.shape)
print(target_test.shape)

(45, 4)
(45,)


Przykłady ze zbiorów już podzielone na dane treningowe i testowe, kolejno: 105 i 45 

In [ ]:
data_train

array([[5.2, 4.1, 1.5, 0.1],
       [6.9, 3.1, 4.9, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [5.6, 2.8, 4.9, 2. ],
       [6.7, 3.3, 5.7, 2.5],
       [6.2, 2.2, 4.5, 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.5, 2.4, 3.7, 1. ],
       [6. , 2.9, 4.5, 1.5],
       [6.4, 3.2, 4.5, 1.5],
       [5.8, 4. , 1.2, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [6.1, 2.9, 4.7, 1.4],
       [5.4, 3.4, 1.7, 0.2],
       [6.4, 3.1, 5.5, 1.8],
       [4.7, 3.2, 1.6, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.9, 2.5, 4.5, 1.7],
       [5.1, 2.5, 3. , 1.1],
       [6.7, 3.1, 5.6, 2.4],
       [4.9, 3.6, 1.4, 0.1],
       [6.9, 3.1, 5.4, 2.1],
       [4.8, 3. , 1.4, 0.3],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [4.4, 3.2, 1.3, 0.2],
       [6.8, 3.2, 5.9, 2.3],
       [7.9, 3.8, 6.4, 2. ],
       [6.5, 3. , 5.5, 1.8],
       [7.6, 3. , 6.6, 2.1],
       [6.3, 2.8, 5.1, 1.5],
       [4.6, 3.4, 1.4, 0.3],
       [5.7, 2.6, 3.5, 1. ],
       [6.7, 2.5, 5.8, 1.8],
       [5.7, 2

In [ ]:
data_test

array([[6.3, 2.3, 4.4, 1.3],
       [6.4, 2.7, 5.3, 1.9],
       [5.4, 3.7, 1.5, 0.2],
       [6.1, 3. , 4.6, 1.4],
       [5. , 3.3, 1.4, 0.2],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.5, 4.9, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 5.1, 1.9],
       [5.5, 2.3, 4. , 1.3],
       [4.9, 3. , 1.4, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [6.8, 3. , 5.5, 2.1],
       [6. , 3.4, 4.5, 1.6],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5. , 3.2, 1.2, 0.2],
       [7.1, 3. , 5.9, 2.1],
       [6.4, 2.8, 5.6, 2.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5.9, 3. , 4.2, 1.5],
       [4.7, 3.2, 1.3, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [5.5, 2.6, 4.4, 1.2],
       [6.8, 2.8, 4.8, 1.4],
       [7.7, 3.8, 6.7, 2.2],
       [6.6, 2.9, 4.6, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [7.2, 3. , 5.8, 1.6],
       [5.8, 2.8, 5.1, 2.4],
       [6.3, 2

### Dane data_train posłużą do przetrenowania modelu

Importowanie klasy LogisticRe... która przechowa model. Tworzenie instancji klasy. Użycie metody fit()- za jej pomocą przetrenowany zostanie model na danych treningowych. Podanie wewnątrz metody danych treningowych.

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(data_train, target_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

Klasy zostały przewidziane na podstawie naszego modelu 

Metoda predict() wykonana na naszym modelu - służy ona do przewidzenia zbioru testowego. WYNIK: klkasy zostały przewidziane na podstawie modelu, który wyuczył się na danych treningowych

In [ ]:
model.predict(data_test)

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 1, 0,
       1])

Przypisanie modelu - to, co przewidzialł - do zmiennej (ona będzie trzymać predykcje zbioru testowego)

In [ ]:
 target_pred = model.predict(data_test)
target_pred

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 1, 0,
       1])

### Użyte zostaną metryki z biblioteki sklearn do oceny modelu

Import z modułu metrics macierzy konfuzji 

target_test (był ustalony na naszych danych testowych); target_pred - to, to, co model przewidział

Wynikiem jest macierz konfuzji. Wazna jest maksymalizacja wartosci po przekątnej. 

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

Importowanie funkcji classification_report() - raportu klasyfikacji do oceny modelu 

Wynikiem: raport klasyfikacji przekazujęcy metryki klas np. precyzja

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(target_test, target_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        14

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



### 2. KLASYFIKACJA BINARNA: dokładnosć modelu i interpretacja graficzna

### Metryki - Problem klasyfikacji:
1. [Import bibliotek](#a0)
2. [Metryki - Klasyfikacja binarna](#a1)
    1. [Accuracy - dokładność klasyfikacji](#a2)
    2. [Macierz konfuzji/pomyłek](#a3)
    3. [Krzywa ROC](#a4)
3. [Metryki - Klasyfikacja wieloklasowa](#a5)   
    1. [Accuracy - dokładność klasyfikacji](#a6)
    2. [Macierz konfuzji/pomyłek](#a7)
    3. [Raport klasyfikacji](#a8)

Import bibliotek

In [ ]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

#### <a name='a1'></a>  3. A. Metryki - Klasyfikacja binarna
#### <a name='a2'></a> Accuracy - Dokładność klasyfikacji

####   $$Accuracy = \frac{correct\ predictions}{total\ predictions} * 100$$

Metryka zlicza liczbę poprawnych predykcji i dzieli przez łaczną liczbę predykcji. Metryki pozwalają ustalić, który model lepiej jest lepszy (dokładniejszy)

W klasyfikacji binarnej do przewidzenia są dwie klasy np. czy klient będzie mieć zdolność kredytową, czy też nie; odróżnianie zdjęć dwóch rodzajów zwierząt. W klasyfikacji wieloklasowej np. odróznianie zdjęć psów, kotów, krów

y_true - klasy prawdziwe; y_pred - klasy, które model przewidział. Tam gdzie ich indeksy się zgadzają predykcja jest poprawna, tam gdzie jest 0 i 1 w tych samych indeksach - są błędy.

In [ ]:

y_true = np.array([1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1])
y_pred = np.array([0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1])

Import metryki, a z niej funkcję. Dwa parametry funkcji  (prawdziwe etykiety i te, które model przewidział)

Wynik: dokładność przewidywań na poziomie 80%

In [ ]:
from sklearn.metrics import  accuracy_score   
accuracy_score(y_true, y_pred)

0.8

Obiekt DataFrame jako słownik z danymi

In [ ]:
 results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
 results

y_true  y_pred
0        1       0
1        0       0
2        1       1
3        1       1
4        0       0
5        1       1
6        1       0
7        0       0
8        1       1
9        0       1
10       1       0
11       1       1
12       0       0
13       1       1
14       1       1
15       0       0
16       1       0
17       1       1
18       0       0
19       1       1
20       1       1
21       1       1
22       0       1
23       1       1
24       1       1
25       0       0
26       1       1
27       1       1
28       0       0
29       1       1

Za pomocą funkcji sort_values() sortowanie danych po kolumnie y_true. Wyświetlają się klasy 0 i 1

In [ ]:
results = results.sort_values(by='y_true')
results

y_true  y_pred
18       0       0
1        0       0
15       0       0
28       0       0
4        0       0
25       0       0
7        0       0
12       0       0
9        0       1
22       0       1
20       1       1
0        1       0
19       1       1
24       1       1
26       1       1
27       1       1
21       1       1
23       1       1
14       1       1
16       1       0
13       1       1
11       1       1
10       1       0
8        1       1
6        1       0
5        1       1
3        1       1
2        1       1
17       1       1
29       1       1

Za pomocą funkcji reset_index() zresetowanie indeksu ponieważ nie zawiera porządku

In [ ]:
results = results.sort_values(by='y_true')
results = results.reset_index(drop=True)
results

y_true  y_pred
0        0       0
1        0       1
2        0       0
3        0       0
4        0       0
5        0       1
6        0       0
7        0       0
8        0       0
9        0       0
10       1       1
11       1       1
12       1       1
13       1       1
14       1       0
15       1       1
16       1       0
17       1       1
18       1       0
19       1       1
20       1       1
21       1       1
22       1       1
23       1       1
24       1       1
25       1       1
26       1       0
27       1       1
28       1       1
29       1       1

Dodanie kolumny simple o powiększonej wartości o 1, w celu sklasyfikowania w których próbkach popełniony został błąd, a w których model działa poprawnie 

In [ ]:
results = results.sort_values(by='y_true')
results = results.reset_index(drop=True)
results['sample'] = results.index + 1
results

y_true  y_pred  sample
0        0       0       1
1        0       0       2
2        0       0       3
3        0       0       4
4        0       1       5
5        0       0       6
6        0       0       7
7        0       0       8
8        0       1       9
9        0       0      10
10       1       1      11
11       1       1      12
12       1       0      13
13       1       1      14
14       1       1      15
15       1       1      16
16       1       1      17
17       1       1      18
18       1       1      19
19       1       0      20
20       1       1      21
21       1       0      22
22       1       1      23
23       1       1      24
24       1       1      25
25       1       1      26
26       1       1      27
27       1       1      28
28       1       0      29
29       1       1      30

### 3. B. KLASYFIKACJA BINARNA: WIZUALIZACJA  

Pierwsza linia - określenie wielkości obiektu figure.
Druga linia - funkcja add_trace(), okreśłenie śladu wykresu; go.Scatter - wykres punktowy. Trzecia linia parametr z - numer próbki, parametr y zmienna y_true - prawdziwe etykiety; podanie w którym miejscu wykres dodać. Czwarta linia - analiza layout

WYKRES: Im bardziej ten drugi wykres jest niepodobny do pierwszego tym gorszy model

In [ ]:
fig = make_subplots(rows=2, cols=1)
fig.add_trace(go.Scatter(x=results['sample'], y=results['y_true'], mode='markers', name='y_true'), row=1, col=1)
fig.add_trace(go.Scatter(x=results['sample'], y=results['y_pred'], mode='markers', name='y_pred'), row=2, col=1)
fig.update_layout(width=900, height=500, title='Klasyfikator binarny')
fig.show()

### 3.C. KLASYFIKACJA BINARNA - macierz konfuzji/pomyłek

To macierz do oceny modeli. Zaimportowanie jej i przekazanie w niej etykiet prawdziwych i prewidzianych. Problem jest dwuklasowy zatem macierz jest 2 na 2. Ważna jest maksymalizacja wartości po przekątnej. 

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)

Utworzenie wykresu . Zmiana kolejności w macierzy. Przekaznie jako kolumny DataPred...


ANALIZA WYKRESU: Klasa true_0 - model przewidział klasę 0 w 8 przypadkach; pomylił się i przewidział klasę 1 w 2 przypadkach. Wartość prawdziawa true_1 - model przewidział klasę 1 w 16 przypadkach poprawnie, w 4 przewidział nastowiast klasę 0. CEL: wartości po przekątnej mają być zmaksymalizowane, a w miescu wartości 2 i 4 winno być 0.

In [ ]:
import plotly.figure_factory as ff

def plot_confusion_matrix(cm):
    cm = cm[::-1]
    cm = pd.DataFrame(cm, columns=['pred_0', 'pred_1'], index=['true_1', 'true_0'])

    fig = ff.create_annotated_heatmap(z=cm.values, x=list(cm.columns), y=list(cm.index), 
                                      colorscale='ice', showscale=True, reversescale=True)
    fig.update_layout(width=400, height=400, title='Confusion Matrix', font_size=16)
    fig.show()

plot_confusion_matrix(cm)

### 3.D. KLASYFIKACJA BINARNA - METRYKI na podstawie macierzy konfuzji

In [ ]:
cm

array([[ 8,  2],
       [ 4, 16]])

Metoda ravel() daje wartosći w postaci tablicy numpy()

In [ ]:
cm.ravel()

array([ 8,  2,  4, 16])

In [ ]:
tn, fp, fn, tp = cm.ravel()

tn - prawdziwie przewidziałem klasę negatywną (klasa negatywna to 0, a pozytywna 1)

tp - miałem klasę pozytywną i przewidziałem pozytywną

In [ ]:
  tn, fp, fn, tp = cm.ravel()
print(f'TN - True Negative: {tn}')
print(f'FP - False Positive: {fp}')
print(f'FN - False Negative: {fn}')
print(f'TP - True Positive: {tp}')

TN - True Negative: 8
FP - False Positive: 2
FN - False Negative: 4
TP - True Positive: 16


CZTERY METRYKI

Jak dużo przewidzieliśmy zdarzeń pozytywnych, gdy klasa była negatywna - to nasza wartość 2 (zobacz na powyższy wykres)

In [ ]:
# Type I error - False Positive Rate
fpr = fp / (fp + tn)
fpr

0.2

Grożny bład mówi jak procentowo wiele negatywnych zdarzeń nie udało nam sie wykryć  (czyli to co w rzeczywistości zaszło a my fąłszywie przewidzieliśmy) Patrz na wykreise wyzej liczba 4.

In [ ]:
# Type II error - False Negative Rate
fnr = fn / (fn + tp)
fnr

0.2

Jak dokładny jest model pod względem przewidywania klasy pierwszej - czyli na naszym wykresie druga kolumna

In [ ]:
# Precision - ile obserwacji przewidywanych jako pozytywne są w rzeczywistości pozytywne
precision = tp / (tp + fp)
print(precision)

0.8888888888888888


Czyli drugi wiersz na nazym wykresie powyżej

In [ ]:
# Recall - jak wiele obserwacji z wzystkich poytywnych sklasyfikowaliśmy jako pozytywne
recall = tp / (tp + fn)
print(recall)

0.8


### 3.E. KLASYFIKACJA BINARNA - krzywa ROC

Import funkcji roc_curve, zwraca ona wartości, pomocne do utworzenia krzywej ROC, m.in. false positive, true positive, wartosć tresh (do wyliczenia krzywej)

In [ ]:
from sklearn.metrics import roc_curve

fpr, tpr, thresh = roc_curve(y_true, y_pred, pos_label=1)
roc = pd.DataFrame({'fpr': fpr, 'tpr': tpr})
roc

fpr  tpr
0  0.0  0.0
1  0.2  0.8
2  1.0  1.0

Tworzenie funkcji, ktora wyświetli powyższy obiekt w bibliotece Plotly (zachowaj tę funkcję dla wyświetlania krzywej ROC)

Pierwsza linia: funkcja przyjmuje dwie wartości. Import danych, przetworzenie i przygotowanie do wykresu.

TWORZYMY WYKRES (ogólne zasady tworzenia): Utworzenie obiektu typu Figure, następnie przekazanie śladygo.Scatter, ustawienie parametru layout (mówi jak wykres ma wyglądać)

INTERPRETACJA WYKRESU: jest jeden model, zatem jedna krzywa. Wszystko ponad linią przerywaną oznacza, ze model działa lepiej niż model losowy

In [ ]:
def plot_roc_curve(y_true, y_pred):
    # Binary classification
    from sklearn.metrics import roc_curve
    fpr, tpr, tresh = roc_curve(y_true, y_pred, pos_label=1)

    fig = go.Figure(data=[go.Scatter(x=roc['fpr'], y=roc['tpr'], line_color='red', name='ROC Curve'),
                        go.Scatter(x=[0, 1], y=[0, 1], mode='lines', line_dash='dash', line_color='navy')],
                    layout=go.Layout(xaxis_title='False Positive Rate',
                                    yaxis_title='True Positive Rate',
                                    title='ROC Curve',
                                    showlegend=False,
                                    width=800,
                                    height=400))
    fig.show()
plot_roc_curve(y_true, y_pred)

### 4. Metryki - KLASYFIKACJA WIELOKLASOWA

a) Accurancy - badanie dokładności klasyfikacji

$$Accuracy = \frac{correct\ predictions}{total\ predictions} * 100$$

Generowanie nowych zmiennych: y_true wartości prawdziwe w naszych danych; y_pred - wartości przewidzane na podstawie modelu

WYNIK: dokładność mocdelu na poziomie 74%

In [ ]:

y_true = np.array([1, 0, 1, 2, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2])
y_pred = np.array([0, 0, 1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 1, 1, 1, 2, 2])

accuracy_score(y_true, y_pred)

0.7241379310344828

b.) Macierz konfuzji/pomyłek

Macierz konfuzji jest 3 na 3 bo mamy trzy klasy

In [ ]:
    cm = confusion_matrix(y_true, y_pred)
    cm

array([[ 6,  1,  0],
       [ 3, 10,  2],
       [ 0,  2,  5]])

c.) Wykres w rozszerzeniu na trzy klasy

INTERPRETACJA WYKRESU:
1.   Wartość prawdziwa klasa 0 (true_0)  została sklasyfikowana przez model (pred_0) jako klasa 0 6-krotnie, natomiast nastąpiła 1 pomyłka i została sklasyfikowana jako klasa 1 (pred_1)

2.  Kolejno klasa pierwsza (true_1) została sklasyfikowana poprawnie 10-krotnie jako klasa pierwsza (pred_1), następnie pojawiły się 3 błędy i została sklasyfikowana jako klasa 0 (pred_0) i 2 błędy jako klasa 2 (pred_2)

3. Następnie klasa 2 (true_2), czyli ta nasza prawdziwa klasa 2, została poprawnie przewidziana 5-krotnie, i bladnie 2-krotnie jako klasa pierwsza (pred_1)









In [ ]:
def plot_confusion_matrix(cm):
    cm = cm[::-1]
    cm = pd.DataFrame(cm, columns=['pred_0', 'pred_1', 'pred_2'], index=['true_2','true_1', 'true_0'])

    fig = ff.create_annotated_heatmap(z=cm.values, x=list(cm.columns), y=list(cm.index), 
                                      colorscale='ice', showscale=True, reversescale=True)
    fig.update_layout(width=400, height=400, title='Confusion Matrix', font_size=16)
    fig.show()

plot_confusion_matrix(cm)

d.) Raport klasyfikacji

In [ ]:
 from sklearn.metrics import classification_report      
 
 print(classification_report(y_true, y_pred ))

              precision    recall  f1-score   support

           0       0.67      0.86      0.75         7
           1       0.77      0.67      0.71        15
           2       0.71      0.71      0.71         7

    accuracy                           0.72        29
   macro avg       0.72      0.75      0.73        29
weighted avg       0.73      0.72      0.72        29



f1-score to średnia harmoniczna wartości poprzednich

Wprowadzenie za liczby nazw, aby wiedzieć do której klasy odnosi się dana metryka

In [ ]:
print(classification_report(y_true, y_pred, target_names=['label_1', 'label_2', 'label_3']))

              precision    recall  f1-score   support

     label_1       0.67      0.86      0.75         7
     label_2       0.77      0.67      0.71        15
     label_3       0.71      0.71      0.71         7

    accuracy                           0.72        29
   macro avg       0.72      0.75      0.73        29
weighted avg       0.73      0.72      0.72        29



### Przejdż do 5.A. REGRESJA - metody oceny modelu - czyli przejdź do kolejnego colabu Sklearn_02