<a href="https://colab.research.google.com/github/NierodkaGrow/Python_new/blob/main/01_math_libraries/02_algebra_lin_i_functstat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.19.5'

#### I. NORMA WEKTOROWA I ODLEGŁOŚĆ PUNKTÓW

1. OBLICZANIE NORMY WEKTOROWEJ W MPRZESTRZENI R DO KWADRATU

In [ ]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [ ]:
np.linalg.norm(v1)

4.0

In [ ]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1)

4.123105625617661

2. OBLICZENIE NORMY WEKTOROWEJ W PRZESTRZENI R DO n

In [ ]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

3. OBLICZANIE ODLEGŁOSCI DWÓCH PUNKTÓW W PRZESTRZENI R2

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

4. ODLEGŁOŚĆ DWÓCH PUNKTÓW W PRZESTRZENI Rn

In [ ]:
p = np.array([3, 0, 3])
q = np.array([0, 4, 5])

np.linalg.norm(p - q)

5.385164807134504

### II. MNOŻENIE MACIERZY

Przykład 1 Z macierz 2x1

In [ ]:
X  = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [ ]:
Z.shape

(2, 1)

Przykład 2

In [ ]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
             [0, -1, 2],
             [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

### III. WYZNACZNIK, M.JEDNOSTKOWA I TRANSPO...

1. WYZNACZNIK MACIERZY

In [ ]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A)

9.999999999999998

In [ ]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A)

9.999999999999998

In [ ]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

2. Ślad macierzy

In [ ]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

3. Macierz jednostkowa

In [ ]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

4. Macierz odwrotna

In [ ]:
A

array([[ 2,  4],
       [-1,  3]])

In [ ]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [ ]:
np.dot(A, B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [ ]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

5. Macierz transponowana

In [ ]:
A

array([[ 2,  4],
       [-1,  3]])

In [ ]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [ ]:
A.T

array([[ 2, -1],
       [ 4,  3]])

### IV. FUNKCJE STATYSTYCZNE

In [ ]:
price = np.array([[12.40, 12.00, 11.80, 12.60, 1000], 
                  [12.10, 12.800, 11.60, 12.50, 2000],
                  [11.30, 12.10, 11.70, 12.40, 3000]])
print(price)

[[  12.4   12.    11.8   12.6 1000. ]
 [  12.1   12.8   11.6   12.5 2000. ]
 [  11.3   12.1   11.7   12.4 3000. ]]


In [ ]:
price.sum()

6145.3

In [ ]:
price.sum(axis=0)

array([  35.8,   36.9,   35.1,   37.5, 6000. ])

In [ ]:
price.sum(axis=1)

array([1048.8, 2049. , 3047.5])

In [ ]:
np.sum(price)

6145.3

In [ ]:
np.min(price)

11.3

In [ ]:
np.min(price, axis=0)

array([  11.3,   12. ,   11.6,   12.4, 1000. ])

In [ ]:
np.min(price, axis=1)

array([11.8, 11.6, 11.3])

In [ ]:
np.max(price)

3000.0

In [ ]:
np.max(price, axis=0)

array([  12.4,   12.8,   11.8,   12.6, 3000. ])

In [ ]:
np.max(price, axis=1)

array([1000., 2000., 3000.])

In [ ]:
np.median(price)

12.4

In [ ]:
np.mean(price)

409.68666666666667

In [ ]:
np.mean(price, axis=0)

array([  11.9333,   12.3   ,   11.7   ,   12.5   , 2000.    ])

In [ ]:
np.mean(price, axis=1)

array([209.76, 409.8 , 609.5 ])

In [ ]:
np.std(price)

874.9900607943435

In [ ]:
np.std(price, axis=0)

array([  0.4643,   0.3559,   0.0816,   0.0816, 816.4966])

In [ ]:
np.std(price,axis=0)

array([ 395.1201,  795.1001, 1195.2501])

KONIEC